# Generated by Django 6.0.4 on 2026-04-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='usersession',
            name='refresh_token_jti',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
