GET http://127.0.0.1:8000/users/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3Mzk4NDU2LCJpYXQiOjE3NzczOTc1NTYsImp0aSI6ImFhNGYxNjMwZDkyNjRhODU4ODk0YzJhMjAyMmIxOThkIiwidXNlcl9pZCI6IjEifQ.J95sQmc7lNljmj807f-mvOUUh7iFMzw752r8DsPE9Ok

### 201 Created
POST http://127.0.0.1:8000/users/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NzA5MDI0LCJpYXQiOjE3NzY3MDgxMjQsImp0aSI6Ijg2OTBkODJiODlhMTQzMzI5YjQ5NGUxYTkxZWZjMTUwIiwidXNlcl9pZCI6IjEiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzX3N0YWZmIjp0cnVlfQ.kSF3L4gHTdRfMpbIJhvQr94mPAQDE3yf78bWLD3ksAA

{
    "email": "j.doe@gmail.com",
    "password": "nfyui2005",
    "first_name": "John",
    "last_name": "Doe",
    "profile": {
      "phone": "+380662017616",
      "address": "5th Avenu, Lviv Ukraine",
      "avatar": null
    }
  }

### 200 OK
POST http://127.0.0.1:8000/users/auth/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "nfyu2005"
}

### 200 OK
POST http://127.0.0.1:8000/users/auth/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "j.doe@gmail.com",
  "password": "nfyui2005"
}

### 200 OK
POST http://127.0.0.1:8000/users/auth/refresh/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NzQ1MTQ1OSwiaWF0IjoxNzc3MzY1MDU5LCJqdGkiOiIwNTNjNDRmNWMzMzU0ZDRlODQzNDcxY2VmMzk5ZGZhMSIsInVzZXJfaWQiOiIxIn0.0YTI4wg-M1YZ_SC1zmqJONgRMcEVn-8jn4jrGNHGlCs"
}

### 200 OK
PUT http://127.0.0.1:8000/users/users/4/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3MzY1NTcxLCJpYXQiOjE3NzczNjQ2NzEsImp0aSI6IjNjZGQ1ODZiOGNmZTQ0NWJiYTQ4NjEzNTg3YWY2YTQxIiwidXNlcl9pZCI6IjQifQ.k_yzqEbcQZrqC3WdDCW_wqI1p8uPpel6cXlHdvTPiNw

{
    "email": "j.doe@gmail.com",
    "password": "nfyu2005",
    "first_name": "John",
    "last_name": "Doe",
    "profile": {
      "phone": "+380662017616",
      "address": "5th Avenu, Lviv Ukraine",
      "avatar": null
    }
  }

### 204 No Content
DELETE  http://127.0.0.1:8000/users/users/4/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3MzY1NTcxLCJpYXQiOjE3NzczNjQ2NzEsImp0aSI6IjNjZGQ1ODZiOGNmZTQ0NWJiYTQ4NjEzNTg3YWY2YTQxIiwidXNlcl9pZCI6IjQifQ.k_yzqEbcQZrqC3WdDCW_wqI1p8uPpel6cXlHdvTPiNw

#########################################################################################################################################
### 200 OK: Get all active sessions
GET http://127.0.0.1:8000/users/sessions/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3Mzk5ODE0LCJpYXQiOjE3NzczOTg5MTQsImp0aSI6IjRmZjU2MTA0MDY5YzQ5NmNhN2Q3MmQyOTg5MzA4NzhmIiwidXNlcl9pZCI6IjEifQ.MNRPZ6wGQzxHdaocCm_-wNkWQRoCE3meg4UpxA1YaEY

### 204 No Content: Revoke a session
DELETE http://127.0.0.1:8000/users/sessions/1c682b5c-e39a-4558-97d4-6d1dc58ac700/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3Mzk5ODE0LCJpYXQiOjE3NzczOTg5MTQsImp0aSI6IjRmZjU2MTA0MDY5YzQ5NmNhN2Q3MmQyOTg5MzA4NzhmIiwidXNlcl9pZCI6IjEifQ.MNRPZ6wGQzxHdaocCm_-wNkWQRoCE3meg4UpxA1YaEY

