# Generated by Django 6.0.4 on 2026-05-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoprating',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='shoprating',
            unique_together={('shop', 'customer')},
        ),
    ]
